# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hogwart',
            new_name='Hogwarts',
        ),
    ]
