# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-22 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0003_users_uploaded_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='fav_books',
        ),
        migrations.RemoveField(
            model_name='users',
            name='uploaded_books',
        ),
        migrations.AddField(
            model_name='books',
            name='uploadeder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded', to='fav_books_app.Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='users_that_favd',
            field=models.ManyToManyField(related_name='fav_books', to='fav_books_app.Users'),
        ),
    ]
