# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20190913_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='These are my notes.'),
            preserve_default=False,
        ),
    ]
