# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-13 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_books_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books_authors_app.authors'),
            preserve_default=False,
        ),
    ]
