# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created', to='course_app.Users'),
            preserve_default=False,
        ),
    ]
